apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
  selector:
    app: accounts-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: accounts-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts-service
        version: v1
    spec:
      containers:
      - name: accounts-service
        image: docker.io/jogdocker/accounts-service-v1:2018.1.1
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: accounts-service
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/Accounts.*
        backend:
          serviceName: accounts-service
          servicePort: 3000
---
